projects/popular_web_vulns/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      get :search
    end

    member do
      get :rank
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

projects/popular_web_vulns/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

projects/popular_web_vulns/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

projects/popular_web_vulns/app/models/user.rb
class User < ApplicationRecord
end

projects/popular_web_vulns/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

projects/popular_web_vulns/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :rank]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = User.find(1)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @search = params[:q].present? ? params[:q].strip : '.*'
    @posts = Post.where("title ~* '#{@search}' or body ~* '#{@search}'")
    render 'index'
  end

  def rank
    @post.rank ||= 0
    @post.rank += 1
    @post.save
    respond_to do |format|
      format.html { redirect_to post_url(@post), notice: 'Successfully ranked'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :published)
    end

    def search_params
      params.require(:q)
    end
end

projects/popular_web_vulns/app/helpers/application_helper.rb
module ApplicationHelper
end

projects/popular_web_vulns/app/helpers/posts_helper.rb
module PostsHelper
end

projects/popular_web_vulns/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PopularWebVulns</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

projects/popular_web_vulns/app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title, size: 100
  .field
    = f.label :body
    = f.text_area :body, cols: 100, rows: 30
  .field
    = f.label :published
    = f.check_box :published
  .actions = f.submit

projects/popular_web_vulns/app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

projects/popular_web_vulns/app/views/posts/index.html.slim
h1 Posts

= link_to 'New Post', new_post_path

= form_tag('/posts/search', method: 'get') do
  = text_field_tag :q, nil, size: 30, value: params[:q]
  = submit_tag 'Search'

  <br>
- if params[:q].present?
  | Records matching your query '#{params[:q].html_safe}':

- @posts.each do |post|
  hr
  h3 = post.title
  p = post.body
  | Published: #{post.published}
  br
  | Created by: #{post.user.login}

  br
  br
  => link_to 'Show', post
  => link_to 'Edit', edit_post_path(post)
  => link_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete

projects/popular_web_vulns/app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

projects/popular_web_vulns/app/views/posts/show.html.slim
p#notice = notice

p
  strong Title:
  = @post.title
p
  strong Body:
  = @post.body.html_safe
p
  strong Published:
  = @post.published
p
  strong Created by:
  = @post.user.login

p
  strong Rank:
  = @post.rank || 0

= link_to 'Rank', rank_post_path(@post)
'|
= link_to 'Edit', edit_post_path(@post)
'|
= link_to 'Back', posts_path